# Generated by Django 4.2.12 on 2025-02-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gametube', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchhistory',
            options={'ordering': ['-watched_at'], 'verbose_name_plural': 'Watch histories'},
        ),
        migrations.RemoveField(
            model_name='watchhistory',
            name='watch_duration',
        ),
        migrations.AlterField(
            model_name='watchhistory',
            name='watched_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
