# Generated by Django 4.2.12 on 2024-12-26 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gametube', '0001_initial'),
    ]

    operations = [
    ]
