# Generated by Django 4.2.12 on 2024-12-26 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gametube', '0003_merge_0002_add_age_field_0002_auto_20241226_1135'),
    ]

    operations = [
    ]
