# Generated by Django 4.2.12 on 2024-12-26 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gametube', '0004_add_age_restriction'),
        ('gametube', '0004_auto_20241226_1139'),
    ]

    operations = [
    ]
