# Generated by Django 4.2.12 on 2025-01-25 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gametube', '0005_merge_20241226_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(default=13),
        ),
    ]
