# Generated by Django 4.2.12 on 2025-01-25 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gametube', '0007_gameboard_age_restriction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameboard',
            name='age_restriction',
            field=models.CharField(choices=[('under18', '18歳未満'), ('over18', '18歳以上')], default='all', max_length=7),
        ),
        migrations.AlterField(
            model_name='video',
            name='age_restriction',
            field=models.CharField(choices=[('under18', '18歳未満'), ('over18', '18歳以上')], default='all', max_length=7),
        ),
    ]
